name: gradle-nuida

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        services:
            redis:
                image: redis
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v3

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Build Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: |
                      build
                      --build-cache
                      --no-daemon

            - name: Deploy to xquare
              uses: team-xquare/xquare-deployment-action@master
              with:
                  environment: prod
                  access_key: ${{ secrets.XQUARE_ACCESS_KEY }}
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  buildargs: |
                      PROFILE=prod
                      JWT_SECRET_KEY=nudianudianudianudia
                      JWT_ACCESS_EXP=3600
                      JWT_REFRESH_EXP=360000
                      JWT_HEADER=Authorization
                      JWT_PREFIX=Bearer
                      DB_URL=${{ secrets.DB_URL }}
                      DB_USERNAME=${{ secrets.DB_USERNAME }}
                      DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                      REDIS_HOST=${{ secrets.REDIS_HOST }}
                      REDIS_PORT=${{ secrets.REDIS_PORT }}
                      API_KEY=${{ secrets.API_KEY }}
                      KAKAO_URL=${{ secrets.KAKAO_URL }}
